version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - "./server:/app:rw"

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app:rw"